stages:
  getdata:
    cmd: python src/get_data.py
  split:
    cmd: python src/split.py
  train:
    cmd: python src/train.py
    params:
    - DecisionTree.max_depth
  evaluvate:
    cmd: python src/evaluate.py
    metrics:
    - report/score.json:
        cache: false
