data_src:
  main_data : 'data/train.csv'
  test_data : 'data/test.csv'

features:
  selected: ["ram", "battery_power", "px_width", "px_height", "mobile_wt",
            "int_memory", "talk_time", "sc_w", "sc_h", "price_range"]
  path : 'data/feature_selected.csv'

DecisionTree:
  max_depth: 12

split_data:
  xtrain : 'data/xtrain.csv'
  xtest : 'data/xtest.csv'

model_path:
  path: 'model/model.pkl'

train_schema:
  n_columns : 10
  col_name : {"ram": "int64", 
              "battery_power": "int64",
              "px_width" : "int64",
              "px_height" : "int64",
              "mobile_wt": "int64",
              "int_memory" : "int64",
              "talk_time" : "int64",
              "sc_w" : "int64", 
              "sc_h" : "int64", 
              "price_range" : "int64"}
  target : "price_range"

test_schema:
  n_columns : 9
  col_name : {"ram": "int64", 
              "battery_power": "int64",
              "px_width" : "int64",
              "px_height" : "int64",
              "mobile_wt": "int64",
              "int_memory" : "int64",
              "talk_time" : "int64",
              "sc_w" : "int64", 
              "sc_h" : "int64"}

report:
  path: 'report/score.json'



